### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Sereath** [TechLord22/TOPExtras#1]
I wasn't sure if we weren't supposed to use this on servers.

https://gist.github.com/Sereath/63e884452befe31c8724ea6ce2719d2e

**Comment by TechLord22** [comment]
The mod is marked client side only, so forge should just ignore it on a server. I tested it with a server installed actually quite a lot so I'm kind of surprised it'd be crashing to be honest. Your crash log link doesn't seem to be working, so I'll need it again if you're able to. Thanks.

**Comment by Sereath** [comment]
Fixed the link.

It actually stopped crashing with 1.0.1
